- name: Deploy Calculator App
  hosts: local

  tasks:
    - name: Remove old containers
      docker_container:
        name: calculator
        state: absent
        force_kill: yes

    - name: Deploy Calculator App
      docker_container:
        name: calculator
        image: krish5726/spe
        state: started
        interactive: yes
        detach: yes

